README.rst
mkdocs.yml
pyproject.toml

@JamesWrigley just quickly updating the README and a few urls
I realize how messed up is the whole naming 🙈

Readme update

---

.github/dependabot/constraints.txt
damnit/gui/plot.py
pyproject.toml

This is the sucessor to mpl-interactions. Fixes #10.

Switch to mpl-pan-zoom

---

damnit/gui/plot.py

Anything with an aspect ratio >4 gets a dynamic aspect ratio by default.
Example:

Set the aspect ratio of images automatically based on their shape

---

damnit/backend/listener.py
damnit/ctxsupport/damnit_ctx.py
damnit/gui/editor.py

These are all unrelated small fixes that I thought I'd smush into a single PR. I'd recommend reviewing each commit by itself.

Assorted minor fixes

---

damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
damnit/gui/main_window.py
damnit/gui/table.py
tests/test_gui.py

These were all found from running pyflakes. It's mostly code cleanup, along with a bug fix in 00bc015.

Code cleanup and bug fixes

---

docs/backend.md
mkdocs.yml

Add docs for configuring Slurm

---

damnit/gui/main_window.py

Spotted in https://github.com/European-XFEL/DAMNIT/pull/119#discussion_r1376379338.

Fix relative heights of the editor widgets

---

damnit/backend/listener.py
damnit/gui/main_window.py

This is the current implementation to allow damnit to run on the online cluster.

Run DAMNIT on the online cluster

---

damnit/migrations.py

Previously these were just skipped.

Migrate the `time_comments` and `variables` tables

---

damnit/gui/table.py

These have pd.NA run/proposal numbers.

Handle standalone comments properly

---

docs/data-storage.md
mkdocs.yml

I wanted to do this before the previous formats are lost to time. I don't think it's necessary to create a *complete* specification, just the broad strokes to give folks an idea.
This is very rudimentary and I'll probably flesh it out with some moar details in the future once v1 is properly finished.

Add some (very) high-level docs for the data format

---

damnit/migrations.py

Tested on HED proposal 4520. Input structure:
```text
├K1
│ ├data   [uint16: 4096 × 4096]
│ └trainId        [uint64: ]
```
Output:
```text
├K1 (1 attributes)
│ ├__xarray_dataarray_variable__  [uint16: 4096 × 4096] (4 attributes)
│ ├dim_0  [float32: 4096] (4 attributes)
│ ├dim_1  [float32: 4096] (4 attributes)
│ └trainId        [uint64: ]
```

Fix migration with scalar coordinates from DataArrays

---

damnit/gui/plot.py

Add maximize / minimize buttons to plot dialog

---

.github/dependabot/constraints.txt

Hopefully this fixes the segfaults we've suddenly started seeing.

Go back to Numpy 1.26.3 for testing

---

damnit/gui/table.py
tests/test_backend.py
tests/test_gui.py

CC @egorsobolev 
~~(I'm gonna try write a test before merging)~~
~~EDIT: on second thoughts writing a test seems a little involved so I might be lazy and leave it for another day.~~
EDIT 2: it was necessary after all :grin:

Fix filtering of disabled runs

---

pyproject.toml

The code to post to Zulip uses requests instead.

Remove unused dependency on zulip package

---

damnit/backend/user_variables.py
damnit/gui/main_window.py
damnit/gui/plot.py
damnit/gui/table.py
tests/test_gui.py

This is kind of necessary as a prelude to wiring the `Cell()` class up to the table in #221, but it's also something I've been working towards for a while.
Pandas is good for working with tables of numbers & doing calculations, but it's not a great match for what we want in a GUI: it doesn't really know about formatting or images, pulling out individual values to display in the GUI is not super efficient, and adding new rows is a bit awkward. Qt provides the [QStandardItemModel](https://doc.qt.io/qt-5/qstandarditemmodel.html) to represent rich tables in memory (as opposed to lazily loaded tables), and of course it fits neatly with GUI expectations, so this is what this PR uses instead of pandas.
I also discovered a neat piece of machinery to allow sorting (QSortFilterProxyModel), which …

Refactor: base GUI table on QStandardItemModel

---

docs/backend.md

I merged too soon :upside_down_face:

Remove the warning about requiring a special token

---

.github/workflows/tests.yml

I was going to do this manually and then I remembered we can do it automagically :stuck_out_tongue: Sneakily copied-and-pasted the code from https://github.com/European-XFEL/EXtra/pull/140.

Create a workflow for automatically publishing new releases

---

damnit/__init__.py
damnit/backend/supervisord.py
damnit/util.py
tests/test_api.py
tests/test_backend.py

This removes the errant dependencies the API had and adds a test for it.

Fix API dependencies

---

docs/api.md

Embarassingly, they were using the wrong variable...

Fix the API examples

---

.github/dependabot/constraints.txt
damnit/backend/extract_data.py
damnit/ctxsupport/ctxrunner.py
damnit/gui/plot.py
docs/backend.md
pyproject.toml
tests/test_backend.py

I've already deployed this to the beta module.

Various fixes & improvements to image results

---

damnit/api.py
damnit/gui/main_window.py
damnit/gui/web_viewer.py
damnit/gui/widgets.py
pyproject.toml

GUI: Plotly widget

---

damnit/api.py
damnit/ctxsupport/ctxrunner.py
damnit/gui/main_window.py
damnit/gui/web_viewer.py
damnit/gui/widgets.py
docs/backend.md
pyproject.toml
tests/conftest.py
tests/test_api.py
tests/test_backend.py

Allow saving plotly figures as a variable result.
GUI widget will be as a separate PR.

Save plotly figure

---

damnit/cli.py
damnit/gui/main_window.py
tests/test_cli.py

This is necessary on hutch computers that don't have OpenGL libraries installed (though ITDM can fix this).

Add an option to force software OpenGL

---

tests/helpers/__init__.py

Hopefully fixes the tests I just broke.

Try to fix broken tests

---

damnit/gui/main_window.py
damnit/gui/plot.py

Special case `xarray.DataArray` in the plot canvas, to retain coordinate and labels information from the data.

Plot xarray

---

damnit/__init__.py

So I can install the API immediately in the new environment.

Silly API bump to use the new dependencies

---

docs/internals.md

I forgot today and had to look up my old PRs to figure out how :facepalm:

Document how to create new releases

---

damnit/api.py

Loading anything from damnit loads the api module (so that you can do `from damnit import Damnit`), but some of these imports can be noticeably slow. Deferring these 3 to where they're used brings `amore-proto db-config` down from 0.6 to 0.3 seconds with a warm cache. The times are worse with a cold cache, but it's hard to get useful measurements for that.
There are other ways we could get a similar result: we could make `damnit.Damnit` lazy-load (I happened to see plotly does a lot of lazy-loading), or we could make separate packages. This way is the smallest change.

Defer some imports in damnit.api

---

damnit/backend/extraction_control.py

My bad :-)
Thanks @tmichela for catching this.

Fix reprocessing from the GUI when the context dir is not the CWD

---

damnit/gui/editor.py

The `dir` argument to NamedTemporaryFile was accidentally deleted in 05cf572, causing context files that rely on executing in the database directory (e.g. to import local files) to fail validation.
I tried to write a test for this but it was trickier than I expected so I opted to just fix it :shrug: Tested on p900460 (CC @daviddoji). This is kinda important because lots of people use local files and otherwise it's not possible to use the editor, so I'll merge this later tonight if there's no objections.

Evaluate the context file in the database directory when validating

---

damnit/gui/plot.py

add the range limit for the xarray branch, similar to the image branch.
Was deployed for a while on the beta module, will merge end of day if there's no comment.

Fix: xarray plot cbar range limit

---

docs/internals.md

Document how to install the API

---

docs/changelog.md
mkdocs.yml

Adds a changelog page to docs since we now version and publish the package.

Add changelog to documentation

---

damnit/gui/table.py

Fix adding new variable without explicit title as column in GUI

---

damnit/gui/editor.py
damnit/gui/main_window.py
damnit/gui/plot.py
damnit/gui/table.py
damnit/gui/theme.py
tests/test_gui.py

Feat: dark theme

---

damnit/gui/process.py

searchable vars list in the reprocessing dialog

---

damnit/ctxsupport/damnit_ctx.py
tests/test_backend.py

fix variable name validation

---

damnit/ctxsupport/ctxrunner.py

Catch errors producing thumbnail

---

damnit/ctxsupport/ctxrunner.py

Catch errors generating thumbnail from matplotlib Figure

---

damnit/gui/table.py
docs/changelog.md
tests/test_gui.py

Adds a visual indicator on columns with active filter:

feat: column filter indicator

---

damnit/backend/listener.py

I think this should resolve the errors we've seen with the database connection in the listener becoming read-only. If there's an error on the second attempt, the listener will crash & be restarted by supervisor.
I thought about just crashing the listener on any error & letting it be restarted, but that took me down a rabbit hole of managing Kafka state, so I decided to do this the way I'd already thought of for now, and maybe come back to that idea later.

Listener: catch SQLite read-only error, reopen database and retry

---

damnit/gui/main_window.py
tests/conftest.py
tests/test_gui.py

Poll the log file changes monitored by the LogViewWindow

feat: LogViewWindow live updates

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

Otherwise if an exception is raised while writing the file would have the usual umask permissions set, which would block other users from overwriting the file.
This was affecting MID so I went ahead and deployed the branch.

Make `add_to_h5_file()` set the file permissions

---

damnit/gui/plot.py
tests/test_gui.py

https://github.com/user-attachments/assets/4ddbba4d-0fc3-4deb-9e1f-cebecbf729fb

feat: add toggle for plotting 2d data as lines
