European-XFEL/DAMNIT

.github/dependabot/constraints.txt

According to @RobertRosca #3 did not fail as it should because `--constraint` does not override the `pyproject.toml` requirements, but add to it, so `<2` + `<3` gets resolved as `<2` from pip.
so we pin it here in the constraint file.

Pin pandas version

---

README.md

I'm not sure how this worked originally, but when testing it I found that the KafkaConsumer will connect to the bootstrap server (localhost) correctly with the AMORE_BROKER variable set, but it will then try to connect to exflwebstor01.desy.de and hang. I'm guessing that when it connects to the bootstrap server it gets a list of all brokers and then tries to connect to them; and since it sees localhost and exflwebstor01.desy.de as different brokers it'll try to connect to exflwebstor01.desy.de too.

Fix the instructions for connecting to XFELs broker offline

---

damnit/backend/extract_data.py

See the commit messages for details, but TL;DR:
- Makes the slurm timeout configurable (and default to 2h)
- Save the slurm logs in a dedicated directory and give the logs and jobs a readable name

Slurm improvements

---

damnit/ctxsupport/ctxrunner.py
docs/backend.md
tests/test_backend.py

Allow setting default arguments for dependencies

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

Previously proc variables executed with `ctxrunner <proposal> <run> proc` (i.e. by the listener) would also open the run with `data="proc"`, which meant that proc variables wouldn't have access to raw non-detector data.

Ensure that proc variables have access to raw data in the run object

---

damnit/backend/extract_data.py

Previously the --match arguments weren't passed to the slurm job, so all variables would be reprocessed.

Make slurm jobs respect --match

---

damnit/backend/db.py
damnit/backend/extract_data.py
damnit/backend/listener.py
damnit/backend/supervisord.py
damnit/ctxsupport/ctxrunner.py

Otherwise it will block other users from doing things like reprocessing runs or starting the listener under a different user, even if the permissions are already loose enough.

Only attempt to change file permissions when the user is the owner

---

pyproject.toml

This is to help prevent hangs, which occasionally happens when writing tests.
I opted for a default of two minutes for each test, which is a bit more than the average time for the entire test suite in CI right now: https://github.com/European-XFEL/DAMNIT/actions

Add a default timeout of two minutes per test

---

damnit/gui/main_window.py

Now it's Y vs X instead of X vs Y, which confused a couple of people before.
(CC @daviddoji)

Swap the plotting widgets axis order so they make sense

---

damnit/ctxsupport/ctxrunner.py

Previously we only checked for `FileNotFoundError`'s, which would be thrown when the proc directory didn't exist at all. But sometimes the calibration pipeline will be really fast and create the proc directory and even create some files by the time the backend has received the migration message and launched a job. In this case `open_run()` will fail with an `Exception` about no HDF5 files being usable, which we didn't catch before and would cause processing of freshly-migrated runs to fail.

Handle all exceptions when checking for proc data

---

damnit/ctxsupport/ctxrunner.py

See the discussion on #24: Numpy gives us a naive datetime representing UTC, but then `.timestamp()` treats it as a local datetime, so we end up 1 or 2 hours out. The numeric timestamp is meant to be a number of seconds since 1st January 1970 UTC.
We have a similar bug in both the extraction side (this change) and the display change), which currently cancel each other out. So when we merge this, we should also fix the display side, which I hope we'll do in #24. And then in theory we should reprocess runs in any existing databases to get the correct timestamp.

Fix getting POSIX timestamps from files

---

damnit/cli.py

This was broken before (since #89) because it would always call `proposal_runs()`, which kinda defeats the purpose of `--mock`.

Fix --mock

---

damnit/cli.py

A very simple one. I tend to forget precisely how our config keys are called, and at the command line I find it more natural to type `-` than `_`. So for the `amore-proto db-config` command, this lets you use e.g. `context-python` instead of `context_python`.
As far as I can see all our settings so far use `_` (`db_id`, `context_python`, `slurm_{partition,reservation,time}`), and I don't think we'd ever want to have two names that differ only in `_` vs. `-`.

Convert - to _ for config keys in db-config command

---

damnit/backend/extract_data.py
damnit/ctxsupport/ctxrunner.py
damnit/gui/editor.py
damnit/gui/main_window.py
docs/backend.md
pyproject.toml
tests/test_backend.py
tests/test_gui.py

Cherry-picked at long last from one of my giant branches :sweat_smile: 
DAMNIT has had theoretical support for separate environments for a while, but semi-recently that broke. The problem is that in some places in `Extractor` and the GUI the context file needed to be loaded, and if the context file does something like `import` a package only available in the other environment, loading it will fail.
My hacky fix is to evaluate the context file in a subprocess, pickle it, and load it again in the main process. This is simple, but a bit ugly since we have to be careful to strip things that aren't pickleable (like functions) from the `ContextFile`. In the future we should do this slightly better by serializing the `ContextFile` to a JSON object or something (which might also be useful for …

Improve support for executing a context file in another environment

---

damnit/backend/extract_data.py
damnit/backend/listener.py
damnit/backend/test_listener.py
damnit/cli.py
damnit/ctxsupport/ctxrunner.py
tests/test_cli.py

At present, variables evaluated in listener subprocesses go into `amore.log`, variables evaluated under `amore-proto reprocess` are logged in the terminal of whoever ran it, and variables evaluated in a Slurm job get a per-job log file in `slurm_logs`. This makes it hard to find any log messages from processing a given run (see #45, #49).
With this change, all DAMNIT processing for a given run will be logged in a file like `process_logs/r123_p4507.out`. I've tried to put some markers in to delineate different processes adding to the file.
<details>
<summary>Example log file</summary>
```
----- Processing r147 (p3210) -----
2023-10-27 19:27:45,343 INFO __main__: args.run_data='raw', args.match=[]
2023-10-27 19:27:45,472 INFO __main__: Ensured p3210 r147 in database …
```

Reorganise run-processing logs

---

damnit/backend/extract_data.py

This could probably be done more cleanly by changing formatters, but it looks ok:
```
│2023-11-01 12:59:10,455 INFO damnit.backend.extract_data: Sent Kafka update to topic 'amore-db-b785369a10c9a0919f685924a587de9d2395ac6d'                                                                                                     │
│2023-11-01 13:05:05,053 INFO damnit.backend.extract_data:                                                                                                                                                                                    │
│ …
```

Add a newline to the log before reprocessing a run

---

damnit/backend/extract_data.py

Previously they weren't logged for variables being locally reprocessed. Also tweaked the formatting of the logging in `__main__` to be more consistent with `reprocess()`.

Log the --match argument during reprocessing as well

---

damnit/gui/main_window.py
damnit/gui/table.py

The actual viewer is super simple for now - just a QPlainTextEdit in read-only mode. But as log files are now per-run, they're relatively small, so I think the ability to filter them is less important. I'm sure we'll want to add features at some point, but we can start simple.

Make per-run logs accessible from the GUI

---

damnit/backend/listener.py

bug introduced in #133 the event name changed to trigger only once all detector corrections are done.

FIX: kafka event for offline correction

---

damnit/backend/api.py
damnit/backend/db.py
damnit/backend/extract_data.py
damnit/cli.py
damnit/context.py
damnit/ctxsupport/ctxrunner.py
damnit/gui/main_window.py
damnit/gui/table.py
damnit/migrations.py
tests/helpers/__init__.py
tests/test_backend.py
tests/test_migrations.py

@JamesWrigley I've done this as a PR targeting your PR (#134) for now. I've tried to keep the commits separate for piece by piece review, but I haven't managed this as neatly as you always do.
Data changes:
- Move the object type hint for un-summarised results into the HDF5 files, stored as a group attribute `damnit_objtype` (25daf2b61cc7981f8106948b119ed79677b68d63).
- I'm only using this for types that we can't store & reconstruct with the native type information, so I don't store a type hint for numpy arrays, numbers or strings. This avoids duplicating this information, but it's an aesthetic choice, and we could easily store an object type for every variable if we prefer.
- Add a column `summary_type` to store additional type hints for summary variables …

Database v1 - further changes

---

damnit/backend/db.py
damnit/cli.py

We plan to migrate all the existing DAMNIT DBs to the new format, so to keep the code simpler we will refuse to open databases until they are migrated.
I've tested this with the GUI - both pointing to a folder on the command line, and selecting a proposal from the dialog - as well as the subcommands proposal, reprocess, new-id & db-config, plus I tested doing a migration (with the `--dry-run` option), which shouldn't be blocked. I used p900385 to try this.
Part of #151.

Refuse to open old databases (except to migrate)

---

damnit/backend/db.py
damnit/backend/extract_data.py
damnit/ctxsupport/ctxrunner.py

In the `run_variables` table, so we know how each summary value was calculated. An empty value means no explicit summarisation - either the function returned a single value already, or we've got the default string representation of an array.
I'm working with a copy of the p900385 database. I went back to the v0 files, re-migrated to get the new `summary_method` field, and then reprocessed a run to put values in there. Here it is in sqlite-glance:
Part of #151

Add summary method (e.g. 'mean', 'sum') to database

---

damnit/ctxsupport/ctxrunner.py

`zoom_ratio` is always <= 1 so it should be multiplied by the `fig.dpi` to get the final DPI.
I don't think it's worth applying this fix to existing databases.

Fix the DPI calculation for creating thumbnails

---

damnit/backend/extract_data.py
damnit/migrations.py
tests/test_backend.py

There was some conversion we were doing when the reduced data was inserted into the database, which wasn't affecting the data sent through Kafka. This resulted in `<PNGData at ...>` reprs showing up in the table instead of thumbnails.
This moves the conversion to where we load the data, so the data we add to the database and the Kafka messages should be more similar. And as a bonus, it also comes out simpler.

Fix sending updates containing PNG thumbnails

---

damnit/backend/api.py
damnit/backend/db.py
damnit/gui/main_window.py
damnit/gui/table.py
tests/test_gui.py

This is mildly cursed because it will reload the database upon deletion. For two reasons:
- There are lingering bugs surrounding moving columns after changing the number of variables, and I don't want to deal with that right now.
- Laziness :innocent: 
My justification is that deleting a variable is something that will (hopefully) occur rarely, and occur when writing the context file for the first time while the database is likely to be empty-ish (so it won't take an obnoxious amount of time to reload). Plus, loading databases isn't *too* awful with the v1 format.
Another thing I'm unsure about is the location of the `api.delete_variable()` function. I put it in `api.py` because I have vague ideas about having a writable wrapper for a future read-only API (exposed to users through a …

Add support for deleting variables

---

damnit/migrations.py

Migration failed on p4448 when it tried to find the max & min of a length 0 dataset. With this change, I was able to complete migration.
```
Traceback (most recent call last):
File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/bin/amore-proto", line 8, in <module>
sys.exit(main())
File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/damnit/cli.py", line 254, in main
migrate_v0_to_v1(db, Path.cwd(), args.dry_run)
File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/damnit/migrations.py", line 207, in migrate_v0_to_v1
max_diff = abs(np.nanmax(data) - np.nanmin(data)).item()
File "<__array_function__ internals>", line 180, in nanmax
File …
```

Don't try to find max_diff from empty datasets

---

README.md
damnit/backend/listener.py
damnit/definitions.py

We still need to know the new topic for migration events (topics are now namespaced).
Do we want to move over the internal updates as well? We're currently using the first test broker that was set up (exflwebstor01).

Listen for incoming events on EuXFEL Kafka broker

---

damnit/gui/main_window.py
damnit/gui/plot.py
damnit/gui/table.py
damnit/gui/user_variables.py
tests/test_gui.py

This may seem like an odd thing to do, but every time I go to work on a feature, I stall, because it seems like every part of the code knows about every other part, so it's hard to work on one piece in isolation.
This is an attempt to unpick that a bit. Specifically, I've tried to make only the `Table` class (renamed `DamnitTableModel`) know that it's actually using a pandas Dataframe to hold the data, so everything else that touches the table needs to go through that class. This isn't 100% complete yet - a couple of places in MainWindow still construct dataframes directly - but it's pretty close, and I wanted to open this before the weekend.
This shouldn't change any functionality at all; the tests are passing for me on Maxwell, and I've also tested it interactively.

Refactor GUI table machinery

---

damnit/backend/api.py
damnit/backend/db.py
damnit/backend/extract_data.py
damnit/backend/user_variables.py
damnit/context.py
damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
damnit/gui/main_window.py
damnit/gui/table.py
damnit/gui/user_variables.py
tests/conftest.py
tests/helpers/__init__.py
tests/test_backend.py

This continues the work I started in #192. My goal this time was to separate the low-level ctxrunner machinery, which parses and runs a `context.py` file, from the database.
Using user-editable variables in the context file has never been turned on, and this PR still doesn't, but it changes the way they will work if/when we do. They would be labelled with an `input#` prefix (e.g. `input#sample_type`) instead of `var#` like variables defined in the context file. A higher level piece would be responsible for finding their values and passing them in when running a context file - the precise mechanism for passing them down still to be decided.
I also moved some of the context file checks into a separate `ContextFile.check()` method. The idea is that we can still read a context file and tell …

Refactor: separate ctxrunner from database

---

damnit/gui/plot.py
tests/test_backend.py

This gets rid of the warnings below - which aren't all of them, but the ones that were easiest to fix quickly.
```
tests/test_backend.py::test_extractor
/home/kluyvert/Code/mid-2833/damnit/ctxsupport/ctxrunner.py:244:
DeprecationWarning: The truth value of an empty array is ambiguous. Returning
False, but in future this will result in an error. Use `array.size > 0` to check
that an array is not empty.
if np.isnan(ts):
tests/test_backend.py::test_extractor
/home/kluyvert/Code/mid-2833/damnit/ctxsupport/ctxrunner.py:254:
DeprecationWarning: parsing timezone aware datetimes is deprecated; this will
raise an error in the future
return np.datetime64(ts, 'us').item().replace(tzinfo=timezone.utc).timestamp()
tests/test_gui.py::test_table_and_plotting
tests/test_gui.py::test_table_and_plotting …
```

Fix some warnings that occur when running the tests

---

damnit/gui/main_window.py
damnit/gui/plot.py

In particular, the plots when you double-click on a cell. Fixed the axis labels for images, and got rid of the 'autoscale' checkbox for plots where it can't do anything.
Before:
After:

Minor improvements to plots

---

damnit/gui/main_window.py
tests/test_gui.py

I think this was missed in one of the recent refactorings.
CC @egorsobolev

Fix call to get_column_states() while exporting to Zulip

---

damnit/migrations.py

We were accidentally skipping all 1D coordinates instead of only scalar coordinates.

Fix migration of old DataArray's

---

damnit/gui/table.py

Previously clicks on the header sections were ignored.

Fix sorting by column in the GUI

---

damnit/gui/table.py

I missed the row selection in a recent refactoring (#192), so sending the table to Zulip would always send the whole table. This should fix that.

Fix selecting rows for sending table to Zulip

---

.github/workflows/tests.yml

Use the current version of all actions. This should fix some warnings about an old version of Node.

Update versions of Github actions in test workflow

---

damnit/backend/db.py
damnit/backend/extract_data.py
damnit/cli.py
damnit/ctxsupport/ctxrunner.py
damnit/gui/main_window.py
damnit/gui/plot.py
damnit/gui/table.py
tests/conftest.py
tests/test_backend.py
tests/test_gui.py

I'm opening this as a draft because it probably still needs some more work, but here's a first draft of storing computed variable metadata in the database.
The metadata is updated whenever a run is processed, and also when launching the GUI - but having an invalid context file (even with syntax errors) no longer prevents the GUI from opening.
Here's a clip of launching the GUI with a proposal that doesn't already have the computed variables in the database. When it first launches, you see the variable IDs like `raw_size` in the column headers, then after a couple of seconds they're updated to the human-friendly titles like 'Raw size [TB]'. The next time you launch the GUI, the titles are there as soon as it opens.
I've made a start on defining a new message structure for notifications …

Store variables from context file in database

---

damnit/gui/main_window.py
damnit/gui/table.py
tests/test_gui.py

This useful for setting parameters ahead of runs being taken.
Example:

Add the ability to pre-create runs in the database

---

.github/dependabot/constraints.txt
.github/workflows/tests.yml
README.md
damnit/gui/main_window.py
pyproject.toml

This pops up a basic Python console when you press F12, to investigate objects in the GUI. It uses my newly published [Adeqt](https://pypi.org/project/adeqt/) package as an optional dependency - if that's not installed, you see an error message when trying to launch the console. I'm thinking we'll install it in the amore modules, so we can easily do a bit of debugging in a running GUI wherever it is, without requiring any special tools.
We could also make it visible in a menu, but for now I thought it might make sense to have it as a lightly hidden feature.

Add a hidden Python console for debugging

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

We already catch exceptions from variable functions, log them and continue computing other variables. But a variable which returned an unexpected type (like a matplotlib `Axes` instead of a `Figure`) would break saving output, with an error like this:
```
...
File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-mid/conda_env/lib/python3.10/site-packages/damnit/ctxsupport/ctxrunner.py", line 575, in main
res.save_hdf5(path)
File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-mid/conda_env/lib/python3.10/site-packages/damnit/ctxsupport/ctxrunner.py", line 453, in save_hdf5
f.create_dataset(path, shape=obj.shape, dtype=obj.dtype)
File "/gpfs/exfel/sw/software/mambaforge/22.11/envs/202401/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
dsid = …
```

Skip over Variables returning unexpected types

---

damnit/ctxsupport/ctxrunner.py
damnit/gui/main_window.py
damnit/gui/plot.py
damnit/util.py
tests/test_gui.py

It is currently only possible to inspect 1d summarized data.
There's a need at HED to explore 2d data. Use case is that from run to run they have either 1 or multiple pulses per train.
In case there's 1 train the resulting data is 1d, but if there's multiple pulses it is 2d (tid vs pulse index). regardless of the case they want the summary data shown in the table and either a scatter plot (1d) or image (2d) when inspecting the variable.
the actual change is in 64f626747abc9a3fed8cb807d4e1e2bfe6e3788d else it's refactoring.

Inspect 2D summarized data

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

A lot of plotting functions from e.g extra-data and EXtra return Axes objects and it's a little annoying to remember to call `.get_figure()` on them every time, so now that's handled automatically.

Add support for returning Axes from variables

---

damnit/gui/main_window.py

Currently the horizontal header disappears if you load a new proposal (`SHIFT+A`):

FIX: hidden header when loading a new proposal in a running GUI

---

damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
damnit/gui/editor.py
damnit/gui/kafka.py
damnit/gui/main_window.py
docs/backend.md
pyproject.toml
tests/test_backend.py
tests/test_gui.py

In a nutshell, DAMNIT will now look for mymdc credentials in `usr/mymdc-credentials.yml` whenever a `mymdc#...` argument is used in a variable, and use them to retrieve mymdc fields (currently just the sample and run type are allowed).
The credentials file must have the format:
```yaml
token: <token>
server: <server-url>
```
Fixes #34.

Mymdc proxy

---

damnit/__init__.py
damnit/api.py
tests/test_api.py

See the comments for details, but TL;DR they're special and aren't inserted in the `variables` table yet so retrieving them would cause errors because we didn't have titles for them.
I also bumped the version, I'm going to roguishly deploy it now because it's a bit annoying to work around in production :see_no_evil: 
The fix will need to stay for the sake of backwards compatibility, but in the future we should add the comment and timestamp to `variables`.

Fix API support for comments and timestamps

---

damnit/ctxsupport/ctxrunner.py

I basically just want to see which variables have been done in larger context files, but while we're at it we may as well record timing information as well.

Log timing after each successful variable computation

---

damnit/ctxsupport/ctxrunner.py

At present, tracebacks covering the context file don't know where the file is, so the relevant entry shows no code:
```
File "/gpfs/exfel/sw/software/xfel_anaconda3/amore-beta/conda_env/lib/python3.10/site-packages/damnit/ctxsupport/ct
xrunner.py", line 330, in execute
data = func(run_data)
File "<string>", line 72, in rep_rate
File "/gpfs/exfel/sw/software/mambaforge/22.11/envs/202401/lib/python3.10/site-packages/extra/components/pulses.py"
, line 971, in __init__
super().__init__(data, source)
...
```
This should fix it so it can show the relevant line of code from the context file as well.

Preserve context file path for tracebacks

---

damnit/gui/table.py

Unlike other rows, these don't have the status column so their `status_item` is None. This caused crashes if there's a standalone comment and the user tried to plot some variables.

Handle standalone comments properly when plotting

---

damnit/backend/listener.py
docs/backend.md

Instead of running extraction as a subprocess of the listener on the login node (or wherever the listener was started), this would run it in the [Solaris cluster](https://confluence.desy.de/display/MXW/Running-single-core-batch-job_302030316.html), which consists of relatively low-powered nodes configured to allow multiple small jobs at once. The `cluster=True` variables are still run on a dedicated node in the main cluster, as before.
The default settings seem to give jobs 2 CPU cores and 4 GB of RAM. We can specify different limits if we want - the nodes seem to have 20 physical cores (40 with hyperthreading) and 256 GB RAM. I'm still figuring out how the different options interact (e.g. `--mem` and `--mem-per-cpu`).
Going over the specified memory limit can get the job killed, whereas …

Evaluate non-cluster variables in Slurm using Solaris cluster

---

damnit/gui/table.py

Because it's hard to quickly figure out what complex figure are on cells.

Show tooltip with full size thumbnail for image items

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

SQS tried to directly return the result of `DataCollection.train_timestamps()` from a variable, which is a dtype not convertable to HDF5 datatype IDs, thus failing when the dataset is written. The current code only prevents `object` arrays, this PR adds a check for convertability for anything that is not an `np.number`.
As a side note, throwing an unchecked exception in the writing code also created some hard to read stack traces full of red herings.

Prevent variable results with dtypes that cannot be converted to HDF5

---

damnit/backend/extract_data.py
damnit/backend/extraction_control.py
damnit/backend/listener.py
damnit/cli.py
damnit/gui/main_window.py
pyproject.toml
tests/conftest.py
tests/helpers/__init__.py
tests/test_api.py
tests/test_backend.py
tests/test_cli.py
tests/test_gui.py

In #256 we made the listener submit jobs to the Solaris cluster to process data, rather than running subprocesses wherever it's running. This extends that to extraction run by `amore-proto reprocess` as well, so restrictions on CPU & memory usage apply consistently, however the processing was launched.
Reprocessing jobs now run in parallel by default (superseding #250), limited by how quickly the solaris cluster starts jobs. A new `--watch` flag switches back to processing one run at a time and showing live output directly in the terminal, but still uses Slurm with the `srun` command.
I see this as a step towards launching reprocessing from the GUI, and having the status of processing jobs visible in the GUI. But I'm leaving those features for a later PR.
I've also refactored a bit. The …

Use Slurm jobs for reprocessing

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

Just ran into this, I'm going to deploy it as a hotfix

Fix returning e.g. bool from variable functions

---

damnit/backend/listener.py
damnit/cli.py
damnit/gui/main_window.py
tests/test_gui.py

This skips the 'backend not running' dialog in the GUI, and the listener also checks for this after 10 minutes with no messages, to shut itself down.
I see two use cases for this:
1. Working with old proposals where you know no new runs are coming, so there's no point running a listener.
2. As part of migration from per-proposal listeners to one central listener, set this for proposals where the central listener will process new runs.

Add a database config option to skip starting a listener

---

damnit/cli.py
tests/helpers/__init__.py
tests/test_cli.py

This lets the `main()` function takes an optional list of command line args, simplifying testing because you don't need to keep modifying `sys.argv` I've used this pattern on various other projects before.

Simplify testing CLI by passing argv in

---

damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
docs/backend.md

This uses the `isinstance_no_import` trick, avoiding loading modules just to check if objects belong to their types.
This reduces the list of packages required for the context Python environment. It can also reduce the overhead of launching the context runner process, although it still loads everything that the context file imports, so the change probably isn't dramatic for most real scenarios.

Defer imports for context file runner code

---

pyproject.toml
tests/test_api.py
tests/test_backend.py

See the commit messages for details. I don't think we need to switch to 3.12 now, but I'm using it locally so it's nice to have it working.
Also ran into this fun bug: https://github.com/matplotlib/matplotlib/issues/28235
Which required creating an environment with: `conda create -c conda-forge -n amore python expat==2.6.1`

Add support for Python 3.12

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

So we don't accidentally run a `cluster=True` variable as part of the 'non-cluster' processing.
I've also made the proc-data promotion a bit more efficient, I hope, by walking through variables in graph order, so we can look only at the immediate dependencies of each variable.
Closes #95

Promote variables to cluster=True if their dependencies are

---

damnit/gui/main_window.py

This fixes segfaults that I came across locally. Presumably the actions were getting GC'd before the slots that use them were signalled.

Save QAction's as class variables

---

damnit/backend/extraction_control.py
damnit/cli.py

I may have been overly pushy about always doing processing in Slurm. Apart from anything else, running locally with the `--mock` option is useful for testing without being on Maxwell.
So this adds an `amore-proto reprocess --direct` option to run processing in subprocesses. Like `--watch` this will process runs one at a time, with live output in the terminal (as well as written to the log file).
cc @tmichela

Add back --direct option to run reprocessing directly on local node

---

damnit/backend/extract_data.py
damnit/backend/extraction_control.py
damnit/ctxsupport/ctxrunner.py
damnit/gui/main_window.py
damnit/gui/process.py
damnit/gui/table.py

Another attempt at this, now that processing happens in Slurm.
Closes #39

(Re)process runs from the GUI

---

damnit/gui/editor.py
damnit/gui/ico/wait_circle.svg
damnit/gui/main_window.py
tests/test_gui.py

I noticed some time ago that a large part of what makes starting the GUI slow is waiting for the context file check, which usually involves starting a subprocess with a different Python, and often also doing some fairly heavy imports in the context file.
This pushes these operations into a separate thread, so we can start using the GUI before the context file check finishes. It also means saving the context file doesn't block the GUI.
Naturally, more async makes the tests a bit more complicated, but I think it's manageable.

Check context file without blocking GUI thread

---

damnit/ctxsupport/ctxrunner.py

I added this in #247, but it must have got lost when I was rebasing #221.
This is just adding back what was already there, so I'll merge it once the CI passes.

Add back log message on successful variable computation

---

damnit/gui/main_window.py

`Cell` is being used in the field, with custom defined summary value as string the GUI thinks there's nothing to plot, although there's still plottable data saved by the variable.

FIX: allow plotting variable with Cell's custom summary value

---

damnit/backend/extract_data.py

I noticed when triggering some reprocessing from the GUI that it evaluated everything in a cluster job, even though I had selected just one (non-cluster) variable to reprocess. I overlooked passing through the new `--var` arguments when preparing to run a cluster job.

Fix passing through --var options to cluster job

---

damnit/__init__.py
damnit/api.py
tests/test_api.py

This is useful for the web interface because the JSON string needs to be sent to the browser.
CC @CammilleCC

Add support for optionally returning the Plotly JSON string

---

damnit/backend/listener.py
tests/conftest.py
tests/test_backend.py

This is mainly to enable external colleagues to start testing DAMNIT without access to slurm.  
It would also be useful later this year if #255 fails dramatically for reasons...

fallback on local execution if slurm fails

---

damnit/cli.py
damnit/gui/main_window.py

Since this cause a few support request already, this activates software openGL by default on maxwell when starting the gui on a non-display node.

Activate software opengl by default on maxwell nodes.

---

tests/test_backend.py

I hope this will avoid the random hard crash during tests I've seen a couple of times recently. It seems to come from garbage collection just after `test_custom_environment` (e.g. [this run](https://github.com/European-XFEL/DAMNIT/actions/runs/10852847320/job/30119808537?pr=335)), so this seems like a good candidate.

Register Qt window created in backend test for cleanup

---

damnit/gui/table.py

`TableView.set_columns` fails since `status` was added to the static columns, handle case with zero columns while setting a new db.
@CammilleCC

FIX: failed to setup new database from the GUI

---

damnit/backend/extract_data.py
damnit/backend/extraction_control.py
damnit/cli.py
damnit/gui/main_window.py

When reprocessing a whole bunch of runs at once, submit them as a Slurm array job, and ask Slurm to limit how many will run at once. This should mitigate the 'database locked' errors, without requiring people to manually batch their jobs and monitor their progress.
The limit is set at 30 concurrent jobs for now. Obviously we can make that configurable.
I've taken the shortcut of using the array task IDs for the run numbers. This avoids having to define a way to communicate 'array task 1 -> run 53', but it does mean that only the run numbers can vary within an array. So the one job we ask to update the variables table in the DB is submitted separately, and if you do `reprocess all` on a database spanning multiple proposals, each proposal would be submitted separately, raising the effective …

Use Slurm array jobs to limit concurrent extraction jobs

---

damnit/backend/extraction_control.py
damnit/cli.py

With 30 I still observe some SQLite locking errors, including from the GUI (which crashed it).

Lower the default slurm concurrency limit to 15

---

tests/test_gui.py

I hope this fixes the abort during tests seen in [this CI run](https://github.com/European-XFEL/DAMNIT/actions/runs/10999646959/job/30540270978?pr=313) on PR #313:
```
Current thread 0x00007fe80e823b80 (most recent call first):
Garbage-collecting
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/pathlib.py", line 574 in _parse_args
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/pathlib.py", line 594 in _from_parts
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/pathlib.py", line 960 in __new__
File "/opt/hostedtoolcache/Python/3.10.15/x64/lib/python3.10/pathlib.py", line 1000 in home
File "/home/runner/work/DAMNIT/DAMNIT/damnit/gui/main_window.py", line 67 in __init__
File "/home/runner/work/DAMNIT/DAMNIT/tests/test_gui.py", line 51 in …
```

Register widgets with qtbot in another test

---

damnit/ctxsupport/ctxrunner.py
docs/backend.md
tests/test_backend.py

This adds support for requesting the techniques information from Mymdc, once @RobertRosca deploys the path in ZWOP.
A run may have multiple techniques associated to it. Here I made the choice to return a single string with all techniques rather than a list, as I think most case will only contain a unique technique (as a mater of fact, the DAQ currently support applying only one technique to a run), and it is easier to handle on the user side. But we can change that if you disagree.

Adds mymdc techniques annotation

---

damnit/backend/extract_data.py

This can be helpful when debugging.
(I'm roguishly gonna go ahead and merge this because it'd be quite useful ATM)

Always log the username and hostname in a processing job

---

damnit/backend/listener.py

The previous logic was not particularly useful...
Unfortunately this is a bit difficult to automatically test so I tested it manually.

Set the log file permissions *before* shutting down

---

damnit/ctxsupport/damnit_ctx.py
damnit/gui/main_window.py
damnit/gui/table.py

Tested interactively. This also fixes a bug where new columns would occasionally show up without a column heading, by ensuring variables always have a title.
cc @tmichela

Watch context file for changes saved separately

---

damnit/ctxsupport/ctxrunner.py
docs/changelog.md
tests/test_backend.py

This makes the thumbnails match what's displayed when the variable is plotted, particularly when there are coordinates being used as ticks along the axes.
Before (thumbnail is upside down):
After:

Use xarray's plotting methods to generate image thumbnails

---

damnit/ctxsupport/damnit_ctx.py
tests/test_backend.py

Failure to generate a summary data would fail writing the entire HDF5 file for that run.

FIX: handle failure generating summary data

---

damnit/backend/db.py
damnit/backend/extract_data.py
damnit/backend/extraction_control.py
damnit/gui/kafka.py
damnit/gui/main_window.py
damnit/gui/process.py
damnit/gui/table.py
tests/helpers/__init__.py
tests/test_backend.py
tests/test_gui.py

Put an icon next to the run number while a processing job is working on a run. The tooltip if you hover over that cell shows more details. This will also mean that new runs appear in the table when the backend starts processing them, instead of when the first job finishes.
The status column would be another option, but we recently discussed hiding that by default.

Show when runs are being processed

---

damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
docs/backend.md
docs/changelog.md
tests/test_backend.py

The controversial one 🙈 
Transient variables' data and summary are not saved.

FEAT: transient variables

---

damnit/gui/main_window.py
damnit/gui/plot.py
damnit/gui/standalone_comments.py
damnit/gui/table.py
damnit/gui/table_filter.py
docs/changelog.md
pyproject.toml
tests/conftest.py
tests/test_backend.py
tests/test_gui.py

Implements basic row filtering based on column values, there are more requirements for this feature, bu that's already a big enough diff and does already something useful.
One regression: support for standalone comments is dropped in the main table. I implemented another table to view them for the proposal that have used them.
[damnit-row-filtering.webm](https://github.com/user-attachments/assets/9db8f950-c58f-4b51-b261-fb40abf0f539)

Basic row filtering

---

damnit/backend/extraction_control.py

Should fix issues with interactive plots from jobs popping up in FastX, and hopefully also issues with jobs from the listener hanging.

Don't pass DISPLAY environment variable to Slurm jobs

---

damnit/ctxsupport/ctxrunner.py
docs/changelog.md

I've sneakily already hotfixed this in the beta module :shushing_face: It would be more correct to find the raw files buuut I'm lazy and don't care much about old proposals anyway.

Handle run timestamps from old proposals with only proc files used

---

damnit/ctxsupport/ctxrunner.py
docs/changelog.md
tests/test_backend.py

I opted to stick with a thumbnail for consistency, the idea being that if the users really want a 1D array they should squeeze it themselves.

Fix thumbnail creation for `DataArray`'s with shape `(1, n)`

---

damnit/ctxsupport/ctxrunner.py
docs/changelog.md
tests/test_backend.py

Previously these would be included even when `cluster=True`, causing them to be executed twice (once in the non-cluster job and again in the cluster job).
I changed the default value of the `cluster` argument in `Context.filter` to make the tests pass, that should be a safe change because every other caller explicitly passes `cluster`.

Fix filtering of non-cluster variables

---

Dockerfile
pyproject.toml

The `build` stage of the Dockerfile was trying to create just enough of the source folder to install the dependencies. This broke on a new version of Flit because the LICENSE file wasn't included. But I don't think there's any problem with just copying the whole git repo folder in, like the app stage does later. So this simplfiies it.
@RobertRosca what do we gain by installing all the dependencies in the build stage and then installing DAMNIT itself separately in the app stage? Could we just install it in the build stage and then copy it across as part of `/app`?

Fix Dockerfile that was missing LICENSE file

---

damnit/gui/plot.py

This quite dramatically improves the image quality, particularly on images with small features and noise.
Before and after:
And another example:
It's such a big improvement I'm gonna sneakily go ahead and merge it :eyes:

Use anti-aliased interpolation for displaying images

---

damnit/backend/extraction_control.py

The GUI calls `submit_multi()` directly so we need to check the database in there instead of `reprocess()`.
@turkot, I'm not sure how this worked for you already if you were reprocessing from the GUI :thinking:

Fix concurrent_jobs usage when reprocessing from the GUI

---

damnit/api.py
damnit/backend/extract_data.py
damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
damnit/gui/table.py
damnit/gui/table_filter.py
docs/backend.md
pyproject.toml
tests/test_backend.py
tests/test_gui.py

Revised presentation:
The colours distinguish general errors (orange) from `raise Skip("some reason")` and extra_data SourceNameError (light grey). The latter comes up a fair bit when sources aren't saved, so I want coding errors to stand out a bit more.

Show errors from executing variables as tooltips on table cells

---

damnit/backend/extraction_control.py

I noticed that when the cluster is busy and jobs have to wait a while, the 'queued' status indicator would disappear. This was because the check for jobs ending without notification was only considering 'RUNNING' state, not 'PENDING'. This should fix that.

Don't treat PENDING Slurm jobs as crashed on job monitor check

---

damnit/ctxsupport/ctxrunner.py
tests/test_backend.py

This caused saving rows in the database for those transient vars leading the table to show extra columns with an integer index for those transient vars:

fix: do not store error for transient variables

---

damnit/gui/table.py

Disable the context menu option when it can't work. I think making it visibly disabled is nicer UX, but we could merge #438 as well for safety, in case there's a corner case I've missed.

Only enable 'View processing logs' action when rows selected

---

damnit/gui/table.py

@philsmt reported this in zulip some while ago, and it has happened to me this week as well.
So we just catch the error here to prevent the gui to crash when we right click on a row (to reprocess/view logs).

fix: prevent the gui to crash if there are no selected rows in the table

---

damnit/api.py
damnit/backend/extraction_control.py
damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
damnit/gui/main_window.py
damnit/gui/table.py
damnit/gui/user_variables.py
damnit/gui/util.py
damnit/gui/web_viewer.py
damnit/gui/widgets.py
damnit/util.py
docs/backend.md
pyproject.toml
tests/conftest.py
tests/test_api.py
tests/test_backend.py
tests/test_gui.py

This adds another layer of partially reduced data between `data` and `summary`. Summary values are shown directly within the table cells, whereas preview data is shown when you double click. This is meant to get rid of the common pattern of paired columns, with one for data and one for a diagnostic plot. Preview can be given a 1D or 2D array, or a matplotlib/plotly figure. For simple cases, arrays are nice because the plot in the GUI can be zoomed, whereas mpl figures are saved as a static image.
Previews can be provided via `Cell`:
```python
@Variable()
def spectra(run):
...
return Cell(spectra_arr, preview=spectra_arr.mean(dim=('trainId', 'pulseId'))
```
The preview function currently only gets the main result from the variable function. We could give it the run, and we could allow it …

Store & show preview data as well as summary value

---

damnit/backend/supervisord.py

This mitigates backends getting confused with each other.

Use a random port for the backend

---

damnit/gui/table.py

This has come up a couple of times recently.

Fix pre-creating runs in an empty table

---

damnit/__init__.py
docs/changelog.md

I would like this because currently the `.errors` entries are showing up when users call `run_vars.keys()`.

Bump version

---

damnit/api.py
damnit/ctxsupport/ctxrunner.py
damnit/ctxsupport/damnit_ctx.py
tests/test_api.py
tests/test_backend.py

`return Cell(None)` caused a crash when saving the results. We decided this should be allowed, and it should be possible to store preview & summary without actual data. This needed a tweak to the API so it can still access such variables: `.read()` will get the summary value, like it does for user-editable variables.
For executing the context file, `return Cell(None)` has the same effect as `return None`: dependent variables will either be skipped, or use a default value if one is given.

Allow variable functions to return Cell(data=None)

---

damnit/gui/util.py

This probably broke when the function was moved in a recent refactor.

Fix icon lookup path

---

damnit/ctxsupport/ctxrunner.py

The previous style only works on 3.10+:
https://discuss.python.org/t/call-staticmethod-from-class-body/14542/2
Also renamed the `_cache` dict to avoid confusion with the `_cache()` decorator.
Not sure how far we want to take backwards compatibility, but this was an easy fix so :shrug: It came up in the wild from an old proposal using a custom Python 3.9 environment.

Fix ctxrunner compatibility with Python 3.9

---

damnit/ctxsupport/ctxrunner.py

When we use print() in context files for debugging, the printed output can appear after the log message that that variable has finished, which is confusing. This is because logs go to stderr, and stdout & stderr have different [buffering rules](https://docs.python.org/3/library/sys.html#sys.stdout).
This should resolve that by flushing stdout after the variable function finishes, before we log anything.

Flush stdout after each variable function

---

damnit/gui/table.py

This fixes a bug @CammilleCC noticed, where empty cells in the DAMNIT table are unexpectedly editable, and trying to accept the edit (e.g. by pressing enter) crashes the GUI.
I thought this would be a fairly quick and easy thing to fix. It was not. I'm still not sure this is the best way to fix it, but it appears to work.
The issue, as I understand it, is that QStandardItemModel claims - via its `.flags()` method - that any cell without an item already present is editable; because without subclassing it will just create a new QStandardItem on demand to store the newly entered text. We would like cells with no item to be non-editable by default. The fix in this PR should do the same as the original where an item exists, but only override the fallback.
A simpler alternative would be to use …

Prevent editing in empty table cells

---

damnit/backend/supervisord.py

Tested by changing the environment of a database and reprocessing some variables.

Update the default `context_python` for the 202502 environment

---

damnit/gui/main_window.py
damnit/util.py
pyproject.toml

- `df.applymap()` was renamed to `.map()` in pandas 2.1.
- The `make_finite` function raised a warning about `.fillna()` downcasting from object dtype. It's not very clear what this is doing - it doesn't get rid of infinities in the data - and it's now only used in one place, so I've simplified the code a bit.

Fix some warnings about pandas deprecations
